# GitLab CI configuration mirroring local `ci:check` and GitHub Actions

image: node:22

variables:
  NODE_ENV: development
  NPM_CONFIG_FUND: "false"
  NPM_CONFIG_AUDIT: "false"

stages:
  - test
  - build

.node_setup: &node_setup
  image: node:22
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
  before_script:
    - node --version
    - npm ci --no-audit --no-fund

quality-and-tests:
  stage: test
  extends: [*node_setup]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - npm run ci:check

build-storybook:
  stage: build
  extends: [*node_setup]
  needs: ["quality-and-tests"]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - npm run build-storybook
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - storybook-static/

build-app:
  stage: build
  extends: [*node_setup]
  needs: ["quality-and-tests"]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - npm run build
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - dist/


