apiVersion: apps/v1
kind: Deployment
metadata:
  name: react18-codebase
  labels:
    app: react18-codebase
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react18-codebase
  template:
    metadata:
      labels:
        app: react18-codebase
    spec:
      containers:
        - name: web
          image: your-registry/react18-codebase:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: VITE_APP_ENV
              value: production
            - name: VITE_API_URL
              value: https://api.example.com
            - name: VITE_WS_URL
              value: wss://ws.example.com
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20

